# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Spelling"

on:  # yamllint disable-line rule:truthy
    workflow_dispatch:
        inputs:
            repository:
                type: "string"
                description: "Repository: username/project"
                required: true

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    codespell_check:
        name: "文A codespell check - ${{ inputs.repository }}"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
            with:
                repository: "${{ inputs.repository }}"
        -
            name: "Search for misspellings"
            uses: "codespell-project/actions-codespell@v2.0"
            with:
                skip: "./.git,package-lock.json,dist,vendor"
                check_hidden: true
                check_filenames: true
                builtin: "clear,rare,informal,usage,code,names"
                ignore_words_list: "master"
