# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Spelling"

on:  # yamllint disable-line rule:truthy
    workflow_dispatch:
        inputs:
            repository:
                type: "string"
                description: "Repository: username/project"
                required: true

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    topy_check:
        name: "文A Topy check - ${{ inputs.repository }}"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
            with:
                repository: "${{ inputs.repository }}"
        -
            name: "Cache pip"
            uses: "actions/cache@v3.3.1"
            with:
                path: "~/.cache/pip"
                key: "${{ runner.os }}-pip-topy"
        -
            name: "Install topy"
            run: |
                pip install --user topy
        -
            name: "Search for misspellings"
            run: |
                "$(python -m site --user-base)/bin/topy" -a $(
                    git ls-files -- \
                        ':!:dist/' ':!:vendor/' \
                        ':!:composer.lock' ':!:yarn.lock' ':!:package-lock.json'
                )
        -
            name: "Check differences to repository"
            run: "git diff --exit-code"
